// src/App.jsx
import Nav from './components/Nav'
import Hero from './components/Hero'
import HowItWorks from './components/HowItWorks'
import Features from './components/Features'
import Testimonial from './components/Testimonial'
import Footer from './components/Footer'
import './App.css'

export default function App() {
  return (
    <div className="app">
      <Nav />
      <main>
        <Hero />
        <HowItWorks />
        <Features />
        <Testimonial />
      </main>
      <Footer />
    </div>
  )
}

// src/App.vue
<template>
  <Nav />
  <main>
    <Hero />
    <HowItWorks />
    <Features />
    <Testimonial />
  </main>
  <Footer />
</template>

<script setup>
import Nav from './components/Nav.vue'
import Hero from './components/Hero.vue'
import HowItWorks from './components/HowItWorks.vue'
import Features from './components/Features.vue'
import Testimonial from './components/Testimonial.vue'
import Footer from './components/Footer.vue'
</script>
